title:            
description:      Welcome to my site.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              //KiaNazarpour.github.io
#https://KiaNazarpour.github.io
disqus_shortname: KiaNazarpour

# Owner/author information
owner:
  name:           
  avatar:         Kia.jpeg
  bio:            An Iranian living in Scotland, the second most beautiful country in the world
  email:          kianoush.nazarpour@ed.ac.uk
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  linkedin: KiaNazarpour
  google_scholar: ZEtKYf8AAAAJ
  github: KiaNazarpour
# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
#links:
#  - title: CV
#    url: /cv/
#  - title: Research
#    url: /research/
#    url: /publications/
#  - title: Vacancies
#    url: /vacancies/
    



# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]